name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - run: mkdir $REPO_NAME && cp -r addons materials scripts $REPO_NAME/
      - run: zip -rq $REPO_NAME-${{ github.ref_name }}.zip $REPO_NAME/
      - id: create_release
        run: gh release create ${{ github.ref_name }} --title "${{ github.ref_name }}"
      - if: success() && steps.create_release.outcome == 'success'
        run: gh release upload ${{ github.ref_name }} $REPO_NAME-*.zip --clobber
